[in.c-main.internal]: DB query failed: [Cloudera][Hardy] %s SemanticException [Error 10001]: Line 1:14 Table not found 'bad' 37000
